create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price bigint, type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price bigint, type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price bigint, type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price bigint, type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price bigint, type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price bigint, type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price bigint, type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price bigint, type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price bigint, type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price bigint, type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price bigint, type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price bigint, type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price bigint, type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price bigint, type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price bigint, type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price bigint, type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price float(53), type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price float(53), type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price float(53), type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer generated by default as identity (start with 1), colour varchar(255), model varchar(255), price float(53), type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer generated by default as identity (start with 1), colour varchar(255), model varchar(255), price float(53), type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create sequence shoe_seq start with 1 increment by 50;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price float(53), type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
create table company (id integer not null, email varchar(255), name varchar(255), phone_number integer, primary key (id));
create table customer (id integer not null, email varchar(255), name varchar(255), phone_number integer, surname varchar(255), primary key (id));
create table shoe (id integer not null, colour varchar(255), model varchar(255), price float(53), type varchar(255), company_id integer, customer_id integer, primary key (id));
alter table shoe add constraint FKt5ko7n35e8llqgljb3vqboxhi foreign key (company_id) references company;
alter table shoe add constraint FKh2wt3nogngsp3abrtfkwcp99y foreign key (customer_id) references customer;
